import React, { createContext, useState, useContext, useEffect } from "react";

const LanguageContext = createContext();

export const translations = {
  en: {
    home: "Home",
    marketplace: "Marketplace",
    pricePrediction: "Price Prediction",
    schemes: "Government Schemes",
    weather: "Weather",
    voiceAssistant: "Voice Assistant",
    profile: "Profile",
    login: "Login",
    register: "Register",
    logout: "Logout",
    adminDashboard: "Admin Dashboard",
    submit: "Submit",
    cancel: "Cancel",
    search: "Search",
    filter: "Filter",
    sortBy: "Sort By",
    viewDetails: "View Details",
    buyNow: "Buy Now",
    contactSeller: "Contact Seller",
    addProduct: "Add Product",
    myProducts: "My Products",
    upload: "Upload",
    edit: "Edit",
    delete: "Delete",
    backToMarketplace: "Back to Marketplace",
    confirmOrder: "Confirm & Place Order",
    smartGatherersTag: "Smart Tribal Gatherers Platform",
    heroTitle: "Empowering Forest Communities through Intelligent Technology",
    heroSubtitle: "Direct market access, AI-driven price prediction, weather updates, and personalized government schemes in your preferred language.",
    getStarted: "Get Started",
    learnMore: "Learn More",
    platformMission: "Platform Mission",
    aboutTitle: "About ForestConnect AI",
    aboutText1: "ForestConnect AI is a digital platform designed to improve the livelihoods of tribal and forest-dependent communities by bridging the digital divide.",
    aboutText2: "By integrating essential agricultural services, machine learning-based price forecasts, government welfare programs, and multilingual speech assistance, we enable tribal gatherers to sell forest produce directly to buyers, bypassing intermediaries.",
    featuresTitle: "Core Features",
    featuresSubtitle: "Comprehensive modules designed specifically for rural communities to enhance income and security.",
    featureMarketplaceTitle: "Direct Marketplace",
    featureMarketplaceDesc: "List and sell minor forest produce directly at fair, standardized rates.",
    featurePredictionTitle: "AI Price Forecasting",
    featurePredictionDesc: "Predict seasonal product demand and optimal market selling times using ML.",
    featureSchemesTitle: "Scheme Advisor",
    featureSchemesDesc: "Discover government welfare and subsidy programs personalized to your profile.",
    featureVoiceTitle: "Voice Assistant",
    featureVoiceDesc: "Navigate the system using speech in local languages, making it accessible to all.",
    exploreMarketplace: "Explore Marketplace →",
    tryPriceForecast: "Try Price Forecast →",
    findEligibleSchemes: "Find Eligible Schemes →",
    weatherAdvisories: "Weather & Advisories",
    weatherAdvisoriesDesc: "Village weather forecasts and agricultural gatherer advisories.",
    checkWeather: "Check Weather",
    healthcareGuidance: "Healthcare Guidance",
    healthcareGuidanceDesc: "First aid steps, nearby health centers, emergency numbers, and medicinal plants.",
    viewHealthGuide: "View Health Guide",
    educationTraining: "Education & Training",
    educationTrainingDesc: "Digital literacy, forest produce processing best practices, and scholarship portals.",
    startLearning: "Start Learning",
    contactTitle: "Get in Touch",
    contactName: "Full Name",
    contactEmail: "Email Address",
    contactMessage: "Message",
    contactSend: "Send Message",
    contactInfoTitle: "Contact Information",
    contactInfoDesc: "Have questions about the platform or GCC enrollment? Reach out to our regional team.",
    contactNote: "* Dedicated helpdesks are set up at Utnoor and Bhadrachalam forest cooperative centers.",
    loginTitle: "Welcome Back",
    loginSubtitle: "Sign in to access your ForestConnect dashboard",
    emailOrMobile: "Mobile Number or Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot Password?",
    noAccount: "Don't have an account?",
    alreadyAccount: "Already have an account?",
    registerTitle: "Create Account",
    registerSubtitle: "Join the forest community marketplace",
    fullName: "Full Name",
    mobileNumber: "Mobile Number",
    emailAddress: "Email Address (Optional)",
    village: "Village",
    district: "District",
    state: "State",
    preferredLanguage: "Preferred Language",
    registerBtn: "Register Now",
    welcome: "Welcome back",
    dashboardTitle: "Your Livelihood Dashboard",
    weatherSummary: "Today's Weather",
    priceTrend: "AI Price Forecast",
    schemesSummary: "Eligible Welfare Schemes",
    profileSummary: "Profile Summary",
    location: "Location",
    activeUploads: "Active Uploads",
    predictedTrendText: "Market prices are currently stable. Best time to sell: Late July.",
    searchPlaceholder: "Search honey, bamboo, herbs...",
    allCategories: "All Categories",
    honey: "Honey & Wax",
    bamboo: "Bamboo & Cane",
    herbs: "Medicinal Herbs & Roots",
    fruits: "Wild Forest Fruits",
    seeds_gums: "Oil Seeds & Gums",
    leaves_fibers: "Leaves & Fibers",
    handicrafts: "Handicrafts & Artifacts",
    spices: "Spices & Condiments",
    quantity: "Quantity",
    marketPrice: "Market Price",
    predictedPrice: "AI Predicted Price",
    price: "Price",
    sellerName: "Seller Name",
    sellerContact: "Seller Contact",
    description: "Description",
    noProducts: "No products found matching your filters.",
    liveTemperature: "Live Temperature",
    feelsLike: "Feels Like",
    humidity: "Relative Humidity",
    windSpeed: "Wind Speed",
    refreshWeather: "Refresh Weather",
    forecast: "5-Day Forecast",
    predictTitle: "AI Price & Demand Predictor",
    predictSubtitle: "Select parameters to project harvest pricing",
    selectProduct: "Select Forest Produce",
    enterQuantity: "Quantity (in kg/pieces)",
    selectMonth: "Month of Sale",
    predictBtn: "Calculate Prediction",
    resultExpectedPrice: "Expected Market Price",
    resultDemand: "Expected Demand Level",
    resultBestTime: "Best Selling Time",
    high: "High",
    medium: "Medium",
    low: "Low",
    schemesTitle: "Government Schemes Portal",
    schemesSubtitle: "Find welfare programs you qualify for",
    inputAge: "Age",
    inputOccupation: "Occupation",
    inputIncome: "Annual Income (₹)",
    inputState: "State",
    findSchemesBtn: "Find Eligible Schemes",
    schemeEligibility: "Eligibility",
    schemeBenefits: "Key Benefits",
    applyNow: "How to Apply",
    voiceTitle: "Voice Assistant Portal",
    voiceSubtitle: "Tap the microphone to navigate using speech",
    voicePrompt: "Press and speak (e.g., 'Show me market prices', 'Find PM Van Dhan Yojana')",
    listening: "Listening... Speak now.",
    processing: "Processing voice input...",
    assistantGreeting: "Hello! How can I help you manage your forest products today?",
    voiceResponse: "I found 3 eligible schemes for you, including PM Van Dhan Yojana. Would you like to read about them?",
    healthcare: "Healthcare Guidance",
    education: "Education & Training",
    healthcareTitle: "Healthcare Guidance",
    healthcareSubtitle: "First aid steps, nearby health centers, emergency numbers, and medicinal plant knowledge",
    educationTitle: "Education & Training",
    educationSubtitle: "Digital literacy, forest produce processing best practices, and scholarship portals",
    digitalLiteracy: "Digital Literacy",
    forestTraining: "Forest Product Training",
    govtResources: "Government Resources",
    childrenEducation: "Children's Education",
    impactGlance: "Impact at a Glance",
    directTrading: "Direct Trading",
    directTradingDesc: "Bypasses middlemen to ensure up to 35% higher profits for tribal gatherers.",
    aiPriceForecasts: "AI Price Forecasts",
    aiPriceForecastsDesc: "Analyzes seasonal markets to recommend most profitable selling months.",
    offlineSupport: "Offline Support",
    offlineSupportDesc: "Runs locally in deep forest areas and syncs automatically when signal returns.",
    quickContacts: "Quick Contacts",
    tribalWelfare: "Tribal Welfare",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    gccGuidelines: "GCC Guidelines",
    rightsReserved: "All Rights Reserved."
  },

  hi: {
    home: "होम",
    marketplace: "मार्केटप्लेस",
    pricePrediction: "मूल्य पूर्वानुमान",
    schemes: "सरकारी योजनाएं",
    weather: "मौसम",
    voiceAssistant: "वॉयस असिस्टेंट",
    profile: "प्रोफ़ाइल",
    login: "लॉगिन",
    register: "पंजीकरण",
    logout: "लॉगआउट",
    adminDashboard: "एडमिन डैशबोर्ड",
    submit: "सबमिट करें",
    cancel: "रद्द करें",
    search: "खोजें",
    filter: "फ़िल्टर",
    sortBy: "क्रमानुसा रखें",
    viewDetails: "विवरण देखें",
    buyNow: "अभी खरीदें",
    contactSeller: "विक्रेता से संपर्क करें",
    addProduct: "उत्पाद जोड़ें",
    myProducts: "मेरे उत्पाद",
    upload: "अपलोड करें",
    edit: "संपादित करें",
    delete: "हटाएं",
    backToMarketplace: "मार्केटप्लेस पर वापस जाएं",
    confirmOrder: "ऑर्डर की पुष्टि करें और ऑर्डर दें",
    smartGatherersTag: "स्मार्ट जनजातीय संग्रहकर्ता मंच",
    heroTitle: "बुद्धिमान तकनीक के माध्यम से वन समुदायों का सशक्तिकरण",
    heroSubtitle: "आपकी पसंदीदा भाषा में सीधा बाजार प्रवेश, एआई-संचालित मूल्य पूर्वानुमान, मौसम अपडेट और व्यक्तिगत सरकारी योजनाएं।",
    getStarted: "शुरू करें",
    learnMore: "और जानें",
    platformMission: "मंच का उद्देश्य",
    aboutTitle: "फॉरेस्टकनेक्ट एआई के बारे में",
    aboutText1: "फॉरेस्टकनेक्ट एआई एक डिजिटल प्लेटफॉर्म है जिसे डिजिटल अंतर को पाटकर जनजातीय और वन-निर्भर समुदायों की आजीविका में सुधार करने के लिए डिज़ाइन किया गया है।",
    aboutText2: "आवश्यक कृषि सेवाओं, मशीन लर्निंग-आधारित मूल्य पूर्वानुमानों, सरकारी कल्याण कार्यक्रमों और बहुभाषी भाषण सहायता को एकीकृत करके, हम जनजातीय संग्रहकर्ताओं को बिचौलियों को दरकिनार करते हुए शहद, बांस, आंवला और जड़ी-बूटियों जैसे वन उपज को सीधे खरीदारों को बेचने में सक्षम बनाते हैं।",
    featuresTitle: "प्रमुख विशेषताएं",
    featuresSubtitle: "आय और सुरक्षा बढ़ाने के लिए ग्रामीण समुदायों के लिए विशेष रूप से डिज़ाइन किए गए व्यापक मॉड्यूल।",
    featureMarketplaceTitle: "प्रत्यक्ष मार्केटप्लेस",
    featureMarketplaceDesc: "उचित, मानकीकृत दरों पर लघु वन उपज को सीधे सूचीबद्ध करें और बेचें।",
    featurePredictionTitle: "एआई मूल्य पूर्वानुमान",
    featurePredictionDesc: "मशीन लर्निंग का उपयोग करके मौसमी उत्पाद मांग और इष्टतम बाजार बिक्री समय का अनुमान लगाएं।",
    featureSchemesTitle: "योजना सलाहकार",
    featureSchemesDesc: "अपनी प्रोफ़ाइल के अनुसार व्यक्तिगत सरकारी कल्याण और सब्सिडी कार्यक्रमों की खोज करें।",
    featureVoiceTitle: "वॉयस असिस्टेंट",
    featureVoiceDesc: "स्थानीय भाषाओं में आवाज का उपयोग करके प्रणाली को नेविगेट करें, जिससे यह सभी के लिए सुलभ हो सके।",
    exploreMarketplace: "मार्केटप्लेस देखें →",
    tryPriceForecast: "मूल्य पूर्वानुमान आजमाएं →",
    findEligibleSchemes: "पात्र योजनाएं खोजें →",
    weatherAdvisories: "मौसम और परामर्श",
    weatherAdvisoriesDesc: "गांव के मौसम के पूर्वानुमान और कृषि संग्रहकर्ता परामर्श।",
    checkWeather: "मौसम देखें",
    healthcareGuidance: "स्वास्थ्य सेवा मार्गदर्शन",
    healthcareGuidanceDesc: "प्राथमिक चिकित्सा चरण, निकटतम स्वास्थ्य केंद्र, आपातकालीन नंबर और औषधीय पौधे।",
    viewHealthGuide: "स्वास्थ्य गाइड देखें",
    educationTraining: "शिक्षा और प्रशिक्षण",
    educationTrainingDesc: "डिजिटल साक्षरता, वन उपज प्रसंस्करण सर्वोत्तम अभ्यास और छात्रवृत्ति पोर्टल।",
    startLearning: "प्रशिक्षण शुरू करें",
    contactTitle: "संपर्क करें",
    contactName: "पूरा नाम",
    contactEmail: "ईमेल पता",
    contactMessage: "संदेश",
    contactSend: "संदेश भेजें",
    contactInfoTitle: "संपर्क जानकारी",
    contactInfoDesc: "प्लेटफ़ॉर्म या जीसीसी नामांकन के बारे में प्रश्न हैं? हमारी क्षेत्रीय टीम से संपर्क करें।",
    contactNote: "* उटनूर और भद्राचलम वन सहकारी केंद्रों पर समर्पित हेल्पडेस्क स्थापित हैं।",
    loginTitle: "पुनः स्वागत है",
    loginSubtitle: "अपने फॉरेस्टकनेक्ट डैशबोर्ड तक पहुँचने के लिए साइन इन करें",
    emailOrMobile: "मोबाइल नंबर या ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    rememberMe: "मुझे याद रखें",
    forgotPassword: "पासवर्ड भूल गए?",
    noAccount: "खाता नहीं है?",
    alreadyAccount: "पहले से ही एक खाता है?",
    registerTitle: "खाता बनाएं",
    registerSubtitle: "वन समुदाय मार्केटप्लेस में शामिल हों",
    fullName: "पूरा नाम",
    mobileNumber: "मोबाइल नंबर",
    emailAddress: "ईमेल पता (वैकल्पिक)",
    village: "गांव",
    district: "जिला",
    state: "राज्य",
    preferredLanguage: "पसंदीदा भाषा",
    registerBtn: "अभी पंजीकरण करें",
    welcome: "पुनः स्वागत है",
    dashboardTitle: "आपकी आजीविका डैशबोर्ड",
    weatherSummary: "आज का मौसम",
    priceTrend: "एआई मूल्य पूर्वानुमान",
    schemesSummary: "पात्र कल्याणकारी योजनाएं",
    profileSummary: "प्रोफ़ाइल सारांश",
    location: "स्थान",
    activeUploads: "सक्रिय अपलोड",
    predictedTrendText: "बाजार की कीमतें वर्तमान में स्थिर हैं। बेचने का सबसे अच्छा समय: जुलाई के अंत में।",
    searchPlaceholder: "शहद, बांस, जड़ी-बूटियों की खोज करें...",
    allCategories: "सभी श्रेणियां",
    honey: "शहद और मोम",
    bamboo: "बांस और बेंत",
    herbs: "औषधीय जड़ी-बूटियां",
    fruits: "जंगली वन फल",
    seeds_gums: "तिलहन और गोंद",
    leaves_fibers: "पत्ते और रेशे",
    handicrafts: "हस्तशिल्प और कलाकृतियां",
    spices: "मसाले",
    quantity: "मात्रा",
    marketPrice: "बाजार मूल्य",
    predictedPrice: "एआई अनुमानित मूल्य",
    price: "मूल्य",
    sellerName: "विक्रेता का नाम",
    sellerContact: "विक्रेता संपर्क",
    description: "विवरण",
    noProducts: "आपके फ़िल्टर से मेल खाने वाले कोई उत्पाद नहीं मिले।",
    liveTemperature: "लाइव तापमान",
    feelsLike: "महसूस होता है",
    humidity: "सापेक्ष आर्द्रता",
    windSpeed: "हवा की गति",
    refreshWeather: "मौसम ताज़ा करें",
    forecast: "5-दिवसीय पूर्वानुमान",
    predictTitle: "एआई मूल्य और मांग पूर्वानुमान",
    predictSubtitle: "उपज मूल्य निर्धारण का अनुमान लगाने के लिए पैरामीटर चुनें",
    selectProduct: "वन उपज चुनें",
    enterQuantity: "मात्रा (किग्रा/नग में)",
    selectMonth: "बिक्री का महीना",
    predictBtn: "पूर्वांचुमान की गणना करें",
    resultExpectedPrice: "अपेक्षित बाजार मूल्य",
    resultDemand: "अपेक्षित मांग का स्तर",
    resultBestTime: "सर्वश्रेष्ठ बिक्री समय",
    high: "उच्च",
    medium: "मध्यम",
    low: "कम",
    schemesTitle: "सरकारी योजनाएं पोर्टल",
    schemesSubtitle: "उन कल्याणकारी कार्यक्रमों को खोजें जिनके आप पात्र हैं",
    inputAge: "आयु",
    inputOccupation: "व्यवसाय",
    inputIncome: "वार्षिक आय (₹)",
    inputState: "राज्य",
    findSchemesBtn: "पात्र योजनाएं खोजें",
    schemeEligibility: "पात्रता",
    schemeBenefits: "प्रमुख लाभ",
    applyNow: "आवेदन कैसे करें",
    voiceTitle: "वॉयस असिस्टेंट पोर्टल",
    voiceSubtitle: "आवाज का उपयोग करके नेविगेट करने के लिए माइक्रोफोन पर टैप करें",
    voicePrompt: "दबाएं और बोलें (जैसे, 'मुझे बाजार मूल्य दिखाएं', 'पीएम वन धन योजना खोजें')",
    listening: "सुन रहा है... अब बोलें।",
    processing: "वॉयस इनपुट संसाधित हो रहा है...",
    assistantGreeting: "नमस्ते! मैं आज आपके वन उत्पादों को प्रबंधित करने में आपकी कैसे मदद कर सकता हूं?",
    voiceResponse: "मुझे आपके लिए पीएम वन धन योजना सहित 3 पात्र योजनाएं मिलीं। क्या आप उनके बारे में पढ़ना चाहेंगे?",
    healthcare: "स्वास्थ्य सेवा मार्गदर्शन",
    education: "शिक्षा और प्रशिक्षण",
    healthcareTitle: "स्वास्थ्य सेवा मार्गदर्शन",
    healthcareSubtitle: "प्राथमिक चिकित्सा चरण, निकटतम स्वास्थ्य केंद्र, आपातकालीन नंबर और औषधीय पौधों का ज्ञान",
    educationTitle: "शिक्षा और प्रशिक्षण",
    educationSubtitle: "डिजिटल साक्षरता, वन उपज प्रसंस्करण सर्वोत्तम अभ्यास और छात्रवृत्ति पोर्टल",
    digitalLiteracy: "डिजिटल साक्षरता",
    forestTraining: "वन उत्पाद प्रशिक्षण",
    govtResources: "सरकारी संसाधन",
    childrenEducation: "बच्चों की शिक्षा",
    impactGlance: "एक नज़र में प्रभाव",
    directTrading: "सीधा व्यापार",
    directTradingDesc: "जनजातीय संग्रहकर्ताओं के लिए 35% तक अधिक लाभ सुनिश्चित करने के लिए बिचौलियों को समाप्त करता है।",
    aiPriceForecasts: "एआई मूल्य पूर्वानुमान",
    aiPriceForecastsDesc: "सबसे लाभदायक बिक्री महीनों की सिफारिश करने के लिए मौसमी बाजारों का विश्लेषण करता है।",
    offlineSupport: "ऑफलाइन सहायता",
    offlineSupportDesc: "गहरे वन क्षेत्रों में स्थानीय रूप से चलता है और सिग्नल वापस आने पर स्वतः सिंक हो जाता है।",
    quickContacts: "त्वरित संपर्क",
    tribalWelfare: "जनजातीय कल्याण",
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा की शर्तें",
    gccGuidelines: "जीसीसी दिशानिर्देश",
    rightsReserved: "सर्वाधिकार सुरक्षित।"
  },

  te: {
    home: "హోమ్",
    marketplace: "మార్కెట్ ప్లేస్",
    pricePrediction: "ధర అంచనా",
    schemes: "ప్రభుత్వ పధకాలు",
    weather: "వాతావరణం",
    voiceAssistant: "వాయిస్ అసిస్టెంట్",
    profile: "ప్రొఫైల్",
    login: "లాగిన్",
    register: "రిజిస్టర్",
    logout: "లాగ్ అవుట్",
    adminDashboard: "అడ్మిన్ డాష్ బోర్డ్",
    submit: "సమర్పించండి",
    cancel: "రద్దు చేయండి",
    search: "వెతకండి",
    filter: "ఫిల్టర్",
    sortBy: "క్రమబద్ధీకరించు",
    viewDetails: "వివరాలు చూడండి",
    buyNow: "ఇప్పుడే కొనండి",
    contactSeller: "అమ్మకందారుని సంప్రదించండి",
    addProduct: "ఉత్పత్తిని జోడించండి",
    myProducts: "నా ఉత్పత్తులు",
    upload: "అప్‌లోడ్",
    edit: "సవరించు",
    delete: "తొలగించు",
    backToMarketplace: "మార్కెట్‌ప్లేస్‌కు తిరిగి వెళ్లండి",
    confirmOrder: "ఆర్డర్ ధృవీకరించండి & ఆర్డర్ చేయండి",
    smartGatherersTag: "స్మార్ట్ గిరిజన సేకరించేవారి ప్లాట్‌ఫారమ్",
    heroTitle: "తెలివైన సాంకేతికత ద్వారా అటవీ సంఘాలకు సాధికారత",
    heroSubtitle: "మీకు ప్రాధాన్యత ఉన్న భాషలో ప్రత్యక్ష మార్కెట్ ప్రాప్యత, AI- ఆధారిత ధర అంచనా, వాతావరణ నవీకరణలు మరియు వ్యక్తిగతీకరించిన ప్రభుత్వ పథకాలు.",
    getStarted: "ప్రారంభించండి",
    learnMore: "మరింత తెలుసుకోండి",
    platformMission: "ప్లాట్‌ఫారమ్ లక్ష్యం",
    aboutTitle: "ఫారెస్ట్ కనెక్ట్ AI గురించి",
    aboutText1: "ఫారెస్ట్ కనెక్ట్ AI అనేది డిజిటల్ వ్యత్యాసాన్ని తొలగించడం ద్వారా గిరిజన మరియు అటవీ ఆధారిత సంఘాల జీవనోపాధిని మెరుగుపరచడానికి రూపొందించబడిన డిజిటల్ వేదిక.",
    aboutText2: "అత్యవసర వ్యవసాయ సేవలు, మెషిన్ లెర్నింగ్ ఆధారిత ధర అంచనాలు, ప్రభుత్వ సంక్షేమ కార్యక్రమాలు మరియు బహుభాషా వాయిస్ సహాయాన్ని అనుసంధానించడం ద్వారా, గిరిజన సేకరణదారులు దళారులను దాటవేసి తేనె, వెదురు, ఉసిరి మరియు మూలికల వంటి అటవీ ఉత్పత్తులను నేరుగా కొనుగోలుదారులకు విక్రయించడానికి మేము వీలు కల్పిస్తాము.",
    featuresTitle: "ముఖ్య లక్షణాలు",
    featuresSubtitle: "ఆదాయం మరియు భద్రతను పెంచడానికి గ్రామీణ వర్గాల కోసం ప్రత్యేకంగా రూపొందించబడిన సమగ్ర మాడ్యూల్స్.",
    featureMarketplaceTitle: "నేరుగా మార్కెట్‌ప్లేస్",
    featureMarketplaceDesc: "సరసమైన, ప్రామాణికమైన ధరలకు చిన్న అటవీ ఉత్పత్తులను నేరుగా జాబితా చేయండి మరియు విక్రయించండి.",
    featurePredictionTitle: "AI ధర అంచనా",
    featurePredictionDesc: "ML ఉపయోగించి రుతువుల వారీగా ఉత్పత్తి డిమాండ్ మరియు సరైన విక్రయ సమయాన్ని అంచనా వేయండి.",
    featureSchemesTitle: "పథకాల సలహాదారు",
    featureSchemesDesc: "మీ ప్రొఫైల్‌కు వ్యక్తిగతీకరించిన ప్రభుత్వ సంక్షేమ మరియు రాయితీ కార్యక్రమాలను కనుగొనండి.",
    featureVoiceTitle: "వాయిస్ అసిస్టెంట్",
    featureVoiceDesc: "స్థానిక భాషలలో వాయిస్ ఉపయోగించి సిస్టమ్‌ను నావిగేట్ చేయండి.",
    exploreMarketplace: "మార్కెట్‌ప్లేస్ చూడండి →",
    tryPriceForecast: "ధర అంచనాను ప్రయత్నించండి →",
    findEligibleSchemes: "అర్హత ఉన్న పథకాలను కనుగొనండి →",
    weatherAdvisories: "వాతావరణం & సలహాలు",
    weatherAdvisoriesDesc: "గ్రామ వాతావరణ అంచనాలు మరియు వ్యవసాయ సేకరణదారుల సలహాలు.",
    checkWeather: "వాతావరణం చూడండి",
    healthcareGuidance: "ఆరోగ్య సంరక్షణ మార్గదర్శకత్వం",
    healthcareGuidanceDesc: "ప్రథమ చికిత్స దశలు, సమీపంలోని ఆరోగ్య కేంద్రాలు, అత్యవసర సంఖ్యలు మరియు మూలికా మొక్కలు.",
    viewHealthGuide: "హెల్త్ గైడ్ చూడండి",
    educationTraining: "విద్య & శిక్షణ",
    educationTrainingDesc: "డిజిటల్ అక్షరాస్యత, అటవీ ఉత్పత్తి ప్రాసెసింగ్ ఉత్తమ పద్ధతులు మరియు స్కాలర్‌షిప్ పోర్టల్‌లు.",
    startLearning: "శిక్షణ ప్రారంభించండి",
    contactTitle: "సంప్రదించండి",
    contactName: "పూర్తి పేరు",
    contactEmail: "ఈమెయిల్ చిరునామా",
    contactMessage: "సందేశం",
    contactSend: "సందేశం పంపండి",
    contactInfoTitle: "సంప్రదింపు సమాచారం",
    contactInfoDesc: "ప్లాట్‌ఫారమ్ లేదా GCC నమోదు గురించి ప్రశ్నలు ఉన్నాయా? మా ప్రాంతీయ బృందాన్ని సంప్రదించండి.",
    contactNote: "* ఉట్నూర్ మరియు భద్రాచలం అటవీ సహకార కేంద్రాలలో ప్రత్యేక హెల్ప్‌డెస్క్‌లు ఏర్పాటు చేయబడ్డాయి.",
    loginTitle: "మళ్లీ స్వాగతం",
    loginSubtitle: "మీ ఫారెస్ట్ కనెక్ట్ డాష్‌బోర్డ్‌ను యాక్సెస్ చేయడానికి సైన్ ఇన్ చేయండి",
    emailOrMobile: "మొబైల్ సంఖ్య లేదా ఈమెయిల్",
    password: "పాస్‌వర్డ్",
    confirmPassword: "పాస్‌వర్డ్‌ను ధృవీకరించండి",
    rememberMe: "నన్ను గుర్తుంచుకో",
    forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
    noAccount: "ఖాతా లేదా?",
    alreadyAccount: "ఇప్పటికే ఖాతా ఉందా?",
    registerTitle: "ఖాతాను సృష్టించండి",
    registerSubtitle: "అటవీ సమాజ మార్కెట్‌ప్లేస్‌లో చేరండి",
    fullName: "పూర్తి పేరు",
    mobileNumber: "మొబైల్ సంఖ్య",
    emailAddress: "ఈమెయిల్ చిరునామా (ঐచ్ఛికం)",
    village: "గ్రామం",
    district: "జిల్లా",
    state: "రాష్ట్రం",
    preferredLanguage: "ప్రాధాన్యత ఉన్న భాష",
    registerBtn: "ఇప్పుడే రిజిస్టర్ అవ్వండి",
    welcome: "మళ్లీ స్వాగతం",
    dashboardTitle: "మీ జీవనోపాధి డాష్‌బోర్డ్",
    weatherSummary: "నేటి వాతావరణం",
    priceTrend: "AI ధర అంచనా",
    schemesSummary: "అర్హత ఉన్న సంక్షేమ పథకాలు",
    profileSummary: "ప్రొఫైల్ సారాంశం",
    location: "ప్రాంతం",
    activeUploads: "యాక్టివ్ అప్‌లోడ్‌లు",
    predictedTrendText: "మార్కెట్ ధరలు ప్రస్తుతం స్థిరంగా ఉన్నాయి. విక్రయించడానికి ఉత్తమ సమయం: జూలై చివరిలో.",
    searchPlaceholder: "తేనె, వెదురు, మూలికల కోసం వెతకండి...",
    allCategories: "అన్ని వర్గాలు",
    honey: "తేనె & మైనం",
    bamboo: "వెదురు",
    herbs: "ఔషధ మూలికలు",
    fruits: "అడవి పండ్లు",
    seeds_gums: "నూనె గింజలు & జిగురు",
    leaves_fibers: "ఆకులు & నారలు",
    handicrafts: "చేతివృత్తులు",
    spices: "మసాలా దినుసులు",
    quantity: "పరిమాణం",
    marketPrice: "మార్కెట్ ధర",
    predictedPrice: "AI అంచనా ధర",
    price: "ధర",
    sellerName: "అమ్మకందారుని పేరు",
    sellerContact: "అమ్మకందారుని సంప్రదింపు సంఖ్య",
    description: "వివరణ",
    noProducts: "మీ ఫిల్టర్‌లకు సరిపోలే ఉత్పత్తులు ఏవీ కనుగొనబడలేదు.",
    liveTemperature: "లైవ్ ఉష్ణోగ్రత",
    feelsLike: "అనిపిస్తుంది",
    humidity: "సాపేక్ష ఆర్ద్రత",
    windSpeed: "గాలి వేగం",
    refreshWeather: "వాతావరణాన్ని రిఫ్రెష్ చేయండి",
    forecast: "5 రోజుల అంచనా",
    predictTitle: "AI ధర & డిమాండ్ అంచనా",
    predictSubtitle: "దిగుబడి ధరను అంచనా వేయడానికి పారామితులను ఎంచుకోండి",
    selectProduct: "అటవీ ఉత్పత్తిని ఎంచుకోండి",
    enterQuantity: "పరిమాణం (కేజీలు/నగదులలో)",
    selectMonth: "విక్రయ నెల",
    predictBtn: "అంచనాను లెక్కించండి",
    resultExpectedPrice: "ఆశించిన మార్కెట్ ధర",
    resultDemand: "ఆశించిన డిమాండ్ స్థాయి",
    resultBestTime: "ఉత్తమ విక్రయ సమయం",
    high: "ఎక్కువ",
    medium: "మధ్యస్థం",
    low: "తక్కువ",
    schemesTitle: "ప్రభుత్వ పథకాల పోర్టల్",
    schemesSubtitle: "మీరు అర్హత సాధించిన సంక్షేమ కార్యక్రమాలను కనుగొనండి",
    inputAge: "వయస్సు",
    inputOccupation: "వృత్తి",
    inputIncome: "వార్షిక ఆదాయం (₹)",
    inputState: "రాష్ట్రం",
    findSchemesBtn: "అర్హత కలిగిన పథకాలను కనుగొనండి",
    schemeEligibility: "అర్హత",
    schemeBenefits: "ముఖ్య ప్రయోజనాలు",
    applyNow: "ఎలా దరఖాస్తు చేయాలి",
    voiceTitle: "వాయిస్ అసిస్టెంట్ పోర్టల్",
    voiceSubtitle: "వాయిస్ ఉపయోగించి నావిగేట్ చేయడానికి మైక్రోఫోన్‌ను నొక్కండి",
    voicePrompt: "నొక్కి మాట్లాడండి (ఉదా., 'మార్కెట్ ధరలను చూపించు', 'పీఎం వన్ ధన్ యోజనను కనుగొను')",
    listening: "వింటోంది... ఇప్పుడు మాట్లాడండి.",
    processing: "వాయిస్ ఇన్‌పుట్ ప్రాసెస్ చేయబడుతోంది...",
    assistantGreeting: "నమస్కారం! నేడు మీ అటవీ ఉత్పత్తులను నిర్వహించడంలో నేను మీకు ఎలా సహాయపడగలను?",
    voiceResponse: "మీ కోసం PM వన్ ధన్ యోజనతో సహా 3 అర్హత ఉన్న పథకాలను కనుగొన్నాను.",
    healthcare: "ఆరోగ్య సంరక్షణ మార్గదర్శకత్వం",
    education: "విద్య & శిక్షణ",
    healthcareTitle: "ఆరోగ్య సంరక్షణ మార్గదర్శకత్వం",
    healthcareSubtitle: "ప్రథమ చికిత్స దశలు, సమీపంలోని ఆరోగ్య కేంద్రాలు, అత్యవసర సంఖ్యలు మరియు మూలికా మొక్కల జ్ఞానం",
    educationTitle: "విద్య & శిక్షణ",
    educationSubtitle: "డిజిటల్ అక్షరాస్యత, అటవీ ఉత్పత్తి ప్రాసెసింగ్ ఉత్తమ పద్ధతులు మరియు స్కాలర్‌షిప్ పోర్టల్‌లు",
    digitalLiteracy: "డిజిటల్ అక్షరాస్యత",
    forestTraining: "అటవీ ఉత్పత్తి శిక్షణ",
    govtResources: "ప్రభుత్వ వనరులు",
    childrenEducation: "పిల్లల విద్య",
    impactGlance: "ఒక చూపులో ప్రభావం",
    directTrading: "నేరుగా వ్యాపారం",
    directTradingDesc: "దళారులను నివారించి గిరిజన సేకరణదారులకు 35% వరకు అధిక లాభాలను అందిస్తుంది.",
    aiPriceForecasts: "AI ధర అంచనాలు",
    aiPriceForecastsDesc: "అత్యంత లాభదాయకమైన విక్రయ నెలలను సిఫార్సు చేయడానికి మార్కెట్‌లను విశ్లేషిస్తుంది.",
    offlineSupport: "ఆఫ్‌లైన్ మద్దతు",
    offlineSupportDesc: "అటవీ ప్రాంతాలలో స్థానికంగా పనిచేస్తుంది మరియు సిగ్నల్ వచ్చినప్పుడు ఆటోమేటిక్‌గా సింక్ అవుతుంది.",
    quickContacts: "త్వరిత పరిచయాలు",
    tribalWelfare: "గిరిజన సంక్షేమం",
    privacyPolicy: "గోప్యతా విధానం",
    termsOfService: "సేవా నిబంధనలు",
    gccGuidelines: "GCC మార్గదర్శకాలు",
    rightsReserved: "సర్వహక్కులు ప్రత్యేకించబడ్డాయి."
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("language") || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
